//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace assignment.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("assignment.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _1__1_ {
            get {
                object obj = ResourceManager.GetObject("1 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Blue_Radial_Gradient_800x600 {
            get {
                object obj = ResourceManager.GetObject("Blue-Radial-Gradient-800x600", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Blue_Radial_Gradient_800x6001 {
            get {
                object obj = ResourceManager.GetObject("Blue-Radial-Gradient-800x6001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Blue_Radial_Gradient_800x6002 {
            get {
                object obj = ResourceManager.GetObject("Blue-Radial-Gradient-800x6002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Blue_Radial_Gradient_800x6003 {
            get {
                object obj = ResourceManager.GetObject("Blue-Radial-Gradient-800x6003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Blue_Radial_Gradient_800x6004 {
            get {
                object obj = ResourceManager.GetObject("Blue-Radial-Gradient-800x6004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Blue_Radial_Gradient_800x6005 {
            get {
                object obj = ResourceManager.GetObject("Blue-Radial-Gradient-800x6005", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Blue_Radial_Gradient_800x6006 {
            get {
                object obj = ResourceManager.GetObject("Blue-Radial-Gradient-800x6006", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Blue_Radial_Gradient_800x6007 {
            get {
                object obj = ResourceManager.GetObject("Blue-Radial-Gradient-800x6007", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap forward_button_512 {
            get {
                object obj = ResourceManager.GetObject("forward_button-512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img_276337 {
            get {
                object obj = ResourceManager.GetObject("img_276337", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap img_2763371 {
            get {
                object obj = ResourceManager.GetObject("img_2763371", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap light_blue_tech_geometric_polygonal_motion_background_video_corporate_animation_hd_1920x1080_nde0ffkig__F0000 {
            get {
                object obj = ResourceManager.GetObject("light-blue-tech-geometric-polygonal-motion-background-video-corporate-animation-h" +
                        "d-1920x1080_nde0ffkig__F0000", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap orange_and_black_background_11558 {
            get {
                object obj = ResourceManager.GetObject("orange-and-black-background-11558", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap polygon_wallpaper_5 {
            get {
                object obj = ResourceManager.GetObject("polygon-wallpaper-5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap vintage_wallpaper_green {
            get {
                object obj = ResourceManager.GetObject("vintage-wallpaper-green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
